import type { RoleId } from "./types";

export type RoleTeam = "village" | "werewolves";
export type RoleCategory = "classic" | "special";
export type RoleGroup = "wolf" | "village" | "specialGoal";

export interface RoleDefinition {
  id: RoleId;
  nameKey: `roles.${RoleId}.name`;
  descriptionKey: `roles.${RoleId}.description`;
  ruleKeys: string[];
  team: RoleTeam;
  category: RoleCategory;
  group: RoleGroup;
  icon: string;
  unique?: boolean;
  handledByApp: boolean;
}

export const roleDefinitions: Record<RoleId, RoleDefinition> = {
  werewolf: {
    id: "werewolf",
    nameKey: "roles.werewolf.name",
    descriptionKey: "roles.werewolf.description",
    ruleKeys: ["night", "win"],
    team: "werewolves",
    category: "classic",
    group: "wolf",
    icon: "moon",
    handledByApp: true,
  },
  villager: {
    id: "villager",
    nameKey: "roles.villager.name",
    descriptionKey: "roles.villager.description",
    ruleKeys: ["day", "win"],
    team: "village",
    category: "classic",
    group: "village",
    icon: "home",
    handledByApp: true,
  },
  seer: {
    id: "seer",
    nameKey: "roles.seer.name",
    descriptionKey: "roles.seer.description",
    ruleKeys: ["inspect", "currentRole"],
    team: "village",
    category: "classic",
    group: "village",
    icon: "eye",
    unique: true,
    handledByApp: true,
  },
  witch: {
    id: "witch",
    nameKey: "roles.witch.name",
    descriptionKey: "roles.witch.description",
    ruleKeys: ["heal", "poison"],
    team: "village",
    category: "classic",
    group: "village",
    icon: "flask",
    unique: true,
    handledByApp: true,
  },
  doctor: {
    id: "doctor",
    nameKey: "roles.doctor.name",
    descriptionKey: "roles.doctor.description",
    ruleKeys: ["heal", "timing"],
    team: "village",
    category: "classic",
    group: "village",
    icon: "cross",
    unique: true,
    handledByApp: true,
  },
  hunter: {
    id: "hunter",
    nameKey: "roles.hunter.name",
    descriptionKey: "roles.hunter.description",
    ruleKeys: ["lastShot", "timing"],
    team: "village",
    category: "classic",
    group: "village",
    icon: "target",
    unique: true,
    handledByApp: true,
  },
  cupid: {
    id: "cupid",
    nameKey: "roles.cupid.name",
    descriptionKey: "roles.cupid.description",
    ruleKeys: ["firstNight", "lovers"],
    team: "village",
    category: "classic",
    group: "village",
    icon: "heart",
    unique: true,
    handledByApp: true,
  },
  fool: {
    id: "fool",
    nameKey: "roles.fool.name",
    descriptionKey: "roles.fool.description",
    ruleKeys: ["goal", "limits"],
    team: "village",
    category: "special",
    group: "specialGoal",
    icon: "badge-help",
    unique: true,
    handledByApp: true,
  },
  villageIdiot: {
    id: "villageIdiot",
    nameKey: "roles.villageIdiot.name",
    descriptionKey: "roles.villageIdiot.description",
    ruleKeys: ["firstDay", "afterwards"],
    team: "village",
    category: "special",
    group: "specialGoal",
    icon: "party-popper",
    unique: true,
    handledByApp: true,
  },
  auraSeer: {
    id: "auraSeer",
    nameKey: "roles.auraSeer.name",
    descriptionKey: "roles.auraSeer.description",
    ruleKeys: ["aura", "limits"],
    team: "village",
    category: "special",
    group: "village",
    icon: "sparkles",
    unique: true,
    handledByApp: true,
  },
  detective: {
    id: "detective",
    nameKey: "roles.detective.name",
    descriptionKey: "roles.detective.description",
    ruleKeys: ["compare", "limits"],
    team: "village",
    category: "special",
    group: "village",
    icon: "search",
    unique: true,
    handledByApp: true,
  },
  alphaWolf: {
    id: "alphaWolf",
    nameKey: "roles.alphaWolf.name",
    descriptionKey: "roles.alphaWolf.description",
    ruleKeys: ["transform", "once"],
    team: "werewolves",
    category: "special",
    group: "wolf",
    icon: "moon-star",
    unique: true,
    handledByApp: true,
  },
  nightGuest: {
    id: "nightGuest",
    nameKey: "roles.nightGuest.name",
    descriptionKey: "roles.nightGuest.description",
    ruleKeys: ["visit", "risk"],
    team: "village",
    category: "special",
    group: "village",
    icon: "bed",
    unique: true,
    handledByApp: true,
  },
  protector: {
    id: "protector",
    nameKey: "roles.protector.name",
    descriptionKey: "roles.protector.description",
    ruleKeys: ["protect", "limits"],
    team: "village",
    category: "special",
    group: "village",
    icon: "shield",
    unique: true,
    handledByApp: true,
  },
  wildChild: {
    id: "wildChild",
    nameKey: "roles.wildChild.name",
    descriptionKey: "roles.wildChild.description",
    ruleKeys: ["model", "conversion"],
    team: "village",
    category: "special",
    group: "village",
    icon: "sprout",
    unique: true,
    handledByApp: true,
  },
  cursed: {
    id: "cursed",
    nameKey: "roles.cursed.name",
    descriptionKey: "roles.cursed.description",
    ruleKeys: ["curse", "secret"],
    team: "village",
    category: "special",
    group: "village",
    icon: "link",
    unique: true,
    handledByApp: true,
  },
  infected: {
    id: "infected",
    nameKey: "roles.infected.name",
    descriptionKey: "roles.infected.description",
    ruleKeys: ["infection", "skip"],
    team: "village",
    category: "special",
    group: "village",
    icon: "biohazard",
    unique: true,
    handledByApp: true,
  },
  littleGirl: {
    id: "littleGirl",
    nameKey: "roles.littleGirl.name",
    descriptionKey: "roles.littleGirl.description",
    ruleKeys: ["peek", "tableRule"],
    team: "village",
    category: "special",
    group: "village",
    icon: "eye-off",
    unique: true,
    handledByApp: false,
  },
  toughGuy: {
    id: "toughGuy",
    nameKey: "roles.toughGuy.name",
    descriptionKey: "roles.toughGuy.description",
    ruleKeys: ["wound", "delay"],
    team: "village",
    category: "special",
    group: "village",
    icon: "dumbbell",
    unique: true,
    handledByApp: true,
  },
};

export const roleOrder: RoleId[] = [
  "werewolf",
  "seer",
  "witch",
  "doctor",
  "hunter",
  "cupid",
  "fool",
  "villageIdiot",
  "auraSeer",
  "detective",
  "alphaWolf",
  "nightGuest",
  "protector",
  "wildChild",
  "cursed",
  "infected",
  "littleGirl",
  "toughGuy",
  "villager",
];

export const selectableRoleOrder = roleOrder.filter((roleId) => roleId !== "villager") as RoleId[];
export const roleIds = Object.keys(roleDefinitions) as RoleId[];
